name: Build and publish NPM package

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions: write-all
    uses: cloudbeds/workflows/.github/workflows/npm-test-build-release-standard-token.yml@main
    secrets: inherit
